### ISSUE TITLE
cmake format, lint, etc.

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#46]
How about including cmake format and linting? There is [cmake-format](https://github.com/cheshirekow/cmake-format-precommit), but it would be more natural to have all cmake stuff here.

**Comment by Takishima** [comment]
`cmake-format` already supports `pre-commit`. See https://cmake-format.readthedocs.io/en/latest/installation.html#pre-commit

**Comment by LecrisUT** [comment]
Indeed it does, and I linked to the precommit repo. But as I said, it would be more natural for it to be included in this repo. Also if you look at the implementation, it could use more improvement to pass arguments etc.

**Comment by Takishima** [comment]
Well, you should be able to pass extra arguments by using the `args: []` key when declaring the hook.

Like so:

```yaml
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        args: [--tab-size, 4]
```
