### ISSUE TITLE
`lizard` does not work

### ISSUE THREAD

**Issue by LecrisUT** [Takishima/cmake-pre-commit-hooks#47]
cmake arguments are not stripped before being passed to the `lizard` executable.

**Comment by Takishima** [comment]
Thanks for reporting this. I will take a look at this issue this week and try to see where the issue lies.

**Comment by Takishima** [comment]
After doing some very basic debugging, I don't seem to be able to reproduce your issues...

I have tried adding a single `print` statement within the `run()` method of `LizardCmd` and using the following configuration:

```yaml
  - repo: local
    hooks:
      - id: lizard
        name: lizard
        entry: ./cmake_pc_hooks/lizard.py
        language: python
        args: [-lcpp, -w]
```

and command line: `pre-commit run --all-files --verbose lizard`, I get the following results:

```
lizard...................................................................Failed
- hook id: lizard
- duration: 0.22s
- exit code: 2

['.editorconfig', '-lcpp', '-w']
['cmake_pc_hooks/lizard.py', '-lcpp', '-w']
['cmake_pc_hooks/__init__.py', '-lcpp', '-w']
...
```
